#ifndef CHIP8_EMULATOR_VERSION_H
#define CHIP8_EMULATOR_VERSION_H

#define CHIP8_VERSION_MAJOR 1
#define CHIP8_VERSION_MINOR 0
#define CHIP8_VERSION_PATCH 0
#define CHIP8_VERSION "1.0.0"

#endif // CHIP8_EMULATOR_VERSION_H
